### ISSUE TITLE
What focal length did you use to shoot the photos in README?

### ISSUE THREAD

**Issue by PhoebusXS** [MartinSeeler/iterm2-material-design#13]
Hi,

Nice colorscheme.

Just courious, what is(are) the focal length(s) used for the photos you put in the README?

Thx.

**Comment by MartinSeeler** [comment]
The images are free stock photos / placeholders. I just pasted the screenshot and tilted it in photoshop into the right place. Therefore I can't answer the question, sorry.

**Comment by MartinSeeler** [comment]
For reference, it was this one: https://www.mockupworld.co/free/big-macbook-mockup-bundle

Had it from another site, but I think this doesn't matter.

**Comment by PhoebusXS** [comment]
> For reference, it was this one: https://www.mockupworld.co/free/big-macbook-mockup-bundle
> 
> Had it from another site, but I think this doesn't matter.

No worries. Thx for the info.
