### ISSUE TITLE
ZSH Theme

### ISSUE THREAD

**Issue by reneruiz** [MartinSeeler/iterm2-material-design#2]
Your terminal setup looks beautiful. Do you mind sharing your ZSH theme?

**Comment by MartinSeeler** [comment]
Thank you!
The prompt I use is called [Pure prompt](https://github.com/sindresorhus/pure) by [Sindre Sorhus](https://github.com/sindresorhus). I will add a link to the `README`.

**Comment by kushalhalder** [comment]
So what ZSH Theme is it? I installed the prompt

**Comment by MartinSeeler** [comment]
It is the theme from this repo and the pure promt, just `ZSH_THEME="pure"` and the iterm2 color settings from [here](https://github.com/MartinSeeler/iterm2-material-design#how-to-use-it).
