### ISSUE TITLE
theme causes vim to be uber bright

### ISSUE THREAD

**Issue by agreco** [MartinSeeler/iterm2-material-design#3]
Love the theme, unfortunately is screws the brightness in terminal vim.. is there away this can be accounted for?

Screen attached:
![screen shot 2016-02-18 at 11 59 07](https://cloud.githubusercontent.com/assets/20005/13142726/0b1b3a46-d637-11e5-9ce3-c8ac526b0d39.png)

**Comment by MartinSeeler** [comment]
Hmm, the bright background is the `black bright` color from the palette. Can you try `set background=dark` in your `~/.vimrc`?

**Comment by agreco** [comment]
here is my .vimrc: https://gist.github.com/agreco/b9deaa16b41c56a12d8f

**Comment by MartinSeeler** [comment]
I can't see anything special. Is your terminal type set to `xterm-256color`? You can see this in the settings of iTerm2 -> Profiles -> Terminal -> Terminal Emulation.

**Comment by agreco** [comment]
Yes it is set to `xterm-256color`, I'm using iTerm2 version `Build 2.9.20160217-nightly`

**Comment by MartinSeeler** [comment]
I think this is an issue with your vim configuration / theme. Since this is not a Vim theme and I'm not an advanced Vim pro, I can only partially try to help you :smile:  Does `:hi Normal ctermbg=None` help?

**Comment by MartinSeeler** [comment]
Is this issue closed with the last suggest, @agreco?

**Comment by agreco** [comment]
Unfortunately not, I did as suggested but some of the color contrast are way too high

<img width="1280" alt="screen shot 2016-03-01 at 21 48 19" src="https://cloud.githubusercontent.com/assets/20005/13443105/7929db40-dff7-11e5-8b46-539504992368.png">

**Comment by agreco** [comment]
Just out of interest which vim colour scheme are you using?

**Comment by MartinSeeler** [comment]
Your screenshot looks like expected. Vim uses the light background in your case. The only thing which helps is to install a vim color scheme. Personally I'm using solarized, but maybe I will generate a color scheme for material design, too.

**Comment by NickClark** [comment]
@MartinSeeler That would be awesome :smile:

**Comment by runar** [comment]
@MartinSeeler Do you think you’ll have a chance to create a vim color scheme? 😃

**Comment by MartinSeeler** [comment]
I have no experience in creating vim color schemes, but any Pull-Request would be appreciated 👍

**Comment by rpereira** [comment]
That would be awesome.
