### ISSUE TITLE
Font colors not changing

### ISSUE THREAD

**Issue by nakulcr7** [MartinSeeler/iterm2-material-design#4]
Hey,

I've followed the instructions as is, but, the font colors aren't changing. The below photos should help you understand my settings

<img width="687" alt="screen shot 2016-02-19 at 12 25 33 am" src="https://cloud.githubusercontent.com/assets/5729612/13167251/85438b9e-d69f-11e5-94f4-9ef5cc1255f0.png">

<img width="692" alt="screen shot 2016-02-19 at 12 27 29 am" src="https://cloud.githubusercontent.com/assets/5729612/13167262/9ad2c79a-d69f-11e5-8a23-5223e4f1ad04.png">

<img width="658" alt="screen shot 2016-02-19 at 12 28 18 am" src="https://cloud.githubusercontent.com/assets/5729612/13167288/ca9135d4-d69f-11e5-8c85-ea90319327cd.png">

<img width="651" alt="screen shot 2016-02-19 at 12 28 33 am" src="https://cloud.githubusercontent.com/assets/5729612/13167289/ca93c722-d69f-11e5-8b80-f9e596ea326b.png">

**Comment by MartinSeeler** [comment]
Which iTerm2 version are you using?

**Comment by nakulcr7** [comment]
Version 3. https://www.iterm2.com/version3.html

**Comment by MartinSeeler** [comment]
Okay, I have not tested it on version 3, since it is still in beta. But I will fix this and provide a version for it soon.

**Comment by MartinSeeler** [comment]
I tested it with iTerm 3 beta, but the colors are working for me. Can you try the script below to test the colors? This will print all color combinations in your terminal. My guess is, that you don't have a prompt which uses colors.

Here is the script:

``` bash
#!/bin/bash
#@auth kesavan.muthuvel
#@desc - bash with colors :)

B=`tput bold`           #BOLD
D=`tput dim`            #DIM
U=`tput sgr 0 1`        #UNDERLINE
U2=`tput smul`          #UNDERLINE2
NOU=`tput rmul`         #NO UNDERLINE
H=`tput smso`           #HIGHLIGHT
X=`tput sgr0`           #RESET
C='tput setaf '         #COLOR


for i in 0 1 2 3 4 5 6 7 ; do
        c=`$C$i` && echo $c${B}I${U}always$NOU $D love \
           ${U2}colors$NOU \& $c${H}GNU/Linux$X
done;
```

**Comment by nakulcr7** [comment]
I'm sorry, I don't understand bash commands. So, I got the below error

<img width="793" alt="screen shot 2016-02-22 at 3 55 38 pm" src="https://cloud.githubusercontent.com/assets/5729612/13232346/d0323918-d97c-11e5-926d-32062c7b35e1.png">

**Comment by MartinSeeler** [comment]
I will close this issue, since your screenshot clearly shows colors. Since the previous screenshots did not (and also had a different prompt), I assume that you just had no colored prompt before and now installed something like oh-my-zsh, which comes with pre-colored prompts.

**Comment by nakulcr7** [comment]
Isnt color supposed to show with commands like git?

**Comment by MartinSeeler** [comment]
This color scheme defines the color codes used by iTerm2. If your git command / directory / arguments are colorized is defined by your prompt and which color codes it uses.
