### ISSUE TITLE
tldr client

### ISSUE THREAD

**Issue by grigorii-horos** [MartinSeeler/iterm2-material-design#6]
What tldr client you use?

**Comment by MartinSeeler** [comment]
[tldr-node-client](https://github.com/tldr-pages/tldr-node-client)
```
❯ tldr --version
1.6.0
```

**Comment by grigorii-horos** [comment]
At me it look ugly
![screenshot_20170411_150254](https://cloud.githubusercontent.com/assets/4980269/24908277/127a8168-1ec8-11e7-8a07-68286ac0610e.png)

**Comment by grigorii-horos** [comment]
I found problem. I don't added ~/.tldrrc
