### ISSUE TITLE
http://www.martinseeler.com/iterm2-material-colors 404

### ISSUE THREAD

**Issue by timpish** [MartinSeeler/iterm2-material-design#8]
Project domain is 404ing.

**Comment by MartinSeeler** [comment]
Thanks, will look into this!

**Comment by gandalfsaxe** [comment]
still doing it 😁

**Comment by MartinSeeler** [comment]
![](https://media.giphy.com/media/vX9WcCiWwUF7G/giphy.gif)

You are right... I'm actually not sure what to write on a dedicated page for this. Maybe I should just remove the link from the repo? What would you expect on a dedicated project site ?

**Comment by gandalfsaxe** [comment]
I don't know, basically a sexed up version of the README.md I guess 😁  Similar to this https://draculatheme.com/iterm/ - however it's not strictly necessary of course.

I'm still on bash and havne't taken the plunge into zsh. If anything, I'd find it useful if there was a little bit of info about whether this is bash/zsh or both, and perhaps a little about making `ls` show colored content in bash (I opted for having `alias ls="ls -G"` in my bash_profile, but I don't know if it's the only/best way to do it). But I don't know how much info is appropriate, I'm not a pro yet.

**Comment by MartinSeeler** [comment]
Thanks for the idea, I think this would be helpful for some people. I will do some experiments in the next days and leave this issue open for now.
